### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zpalmtree** [turtlecoin/turtlecoin-mobile-wallet#63]
- [x] Prune inputs older than 5000 blocks

In processBlock,
```
if (block.blockHeight % 5000 === 0)
{
    removeSpentInputs(block.blockHeight - 5000)
}
```

This should decrease file sizes for large wallets preventing OOM crashes.

- [x] Optimize database occasionally, preferably in background.

Store a 'last optimized' flag. Maybe... `if (lastOptimized > 1 day)`:
Do in background to be less disruptive.

`if (lastOptimized > 2 days)`:
Do in foreground since it appears background sync isn't running.

- [ ] Use turtlepay api to waive fees for turtlepay transactions

- [ ] Env vars for sentry so we don't get notifications from brainlets forking

- [x] Payee additions not showing up on transfer screen, probably need to add `extraData` prop and subscribe to `Globals.update`

- [ ] Background syncing when locked / on startup (DB stuph changed..)
